language: node_js
node_js:
  - "14.15.4"
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: surge
  skip_cleanup: true
  domain: dnd-name-gen.surge.sh
  project: ./build/
on:
  branch: master